#include "Music.h"

#include <Gamebuino-Meta.h>
#undef min
#undef max

#include <algorithm>

#include "CellCountHistory.h"
#include "LifeCa.h"
#include "LivelinessCheck.h"

namespace Gamebuino_Meta {

// This file is automatically generated using import-from-p8.py
//
// Manually patched to:
// - Remove duplicate patterns
// - Remove unneeded SFX, patterns and songs

const NoteSpec sfx10Notes[32] = {
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
};
const TuneSpec sfx10 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx10Notes
};
const NoteSpec sfx11Notes[32] = {
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
};
const TuneSpec sfx11 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx11Notes
};
const NoteSpec sfx12Notes[32] = {
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::E2, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::E2, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
};
const TuneSpec sfx12 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx12Notes
};
const NoteSpec sfx13Notes[32] = {
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::E2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::E2, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A3, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::E2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::E2, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A3, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
};
const TuneSpec sfx13 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx13Notes
};
const NoteSpec sfx14Notes[32] = {
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx14 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx14Notes
};
const NoteSpec sfx15Notes[32] = {
    NoteSpec { .note=Note::F2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::D2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::B2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::B2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::B2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::B2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::B2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C3, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx15 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx15Notes
};
const NoteSpec sfx16Notes[32] = {
    NoteSpec { .note=Note::F2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx16 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx16Notes
};
const NoteSpec sfx17Notes[32] = {
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::D3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
};
const TuneSpec sfx17 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx17Notes
};
const NoteSpec sfx18Notes[32] = {
    NoteSpec { .note=Note::F2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::F3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::D2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::B2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::B2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::G3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
};
const TuneSpec sfx18 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx18Notes
};
const NoteSpec sfx19Notes[32] = {
    NoteSpec { .note=Note::F2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::F3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::G2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::E2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::B2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::E3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::A2, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A2, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::B2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::D3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::E3, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
};
const TuneSpec sfx19 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx19Notes
};
const NoteSpec sfx20Notes[32] = {
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::B3, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::B3, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A3, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A3, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
};
const TuneSpec sfx20 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx20Notes
};
const NoteSpec sfx21Notes[32] = {
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
};
const TuneSpec sfx21 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx21Notes
};
const NoteSpec sfx22Notes[32] = {
    NoteSpec { .note=Note::A4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::A4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx22 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx22Notes
};
const NoteSpec sfx23Notes[32] = {
    NoteSpec { .note=Note::F3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::F3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::F3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::F3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx23 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx23Notes
};
const NoteSpec sfx24Notes[32] = {
    NoteSpec { .note=Note::F3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::F3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::F3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::D4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::E3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx24 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx24Notes
};
const NoteSpec sfx25Notes[32] = {
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::E3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx25 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx25Notes
};
const NoteSpec sfx26Notes[32] = {
    NoteSpec { .note=Note::E4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::D4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::B3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx26 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx26Notes
};
const NoteSpec sfx27Notes[32] = {
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::E5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::E5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx27 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx27Notes
};
const NoteSpec sfx28Notes[32] = {
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::E5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::A5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx28 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx28Notes
};
const NoteSpec sfx29Notes[32] = {
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::E5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx29 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx29Notes
};
const NoteSpec sfx30Notes[32] = {
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx30 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx30Notes
};
const NoteSpec sfx31Notes[32] = {
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::B5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E5, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx31 = TuneSpec {
    .noteDuration = 22, .loopStart = 32, .numNotes = 32, .notes = sfx31Notes
};

const TuneSpec* adaptivePattern1Tunes[4] = {
  &sfx13, &sfx19, &sfx26, &sfx31
};
PatternSpec adaptivePattern1 = PatternSpec {
  .numTunes = 4, .tunes = adaptivePattern1Tunes
};
const TuneSpec* adaptivePattern2Tunes[4] = {
  &sfx13, &sfx19, &sfx26, &sfx31
};
PatternSpec adaptivePattern2 = PatternSpec {
    .numTunes = 4, .tunes = adaptivePattern2Tunes
};
PatternSpec *const adaptivePatterns[2] = {
    &adaptivePattern1,
    &adaptivePattern2,
};
const SongSpec adaptiveSong = SongSpec {
  .loopStart = 0, .numPatterns = 2, .patterns = adaptivePatterns
};
const TuneSpec* *const adaptivePatternTunes[2] = {
  adaptivePattern1Tunes,
  adaptivePattern2Tunes
};

// Each row specifies the SFX for a given layer.
// Each row consists of four pairs, arranged for increased liveliness.
const TuneSpec *const adaptiveTunes[8 * NUM_CA_LAYERS] = {
  &sfx10, &sfx10,  &sfx11, &sfx11,  &sfx12, &sfx12,  &sfx13, &sfx13,
  &sfx14, &sfx14,  &sfx15, &sfx16,  &sfx17, &sfx17,  &sfx18, &sfx19,
  &sfx20, &sfx21,  &sfx22, &sfx22,  &sfx23, &sfx24,  &sfx25, &sfx26,
  &sfx27, &sfx28,  &sfx29, &sfx29,  &sfx30, &sfx30,  &sfx31, &sfx31,
};

} // Namespace

int pattern_to_update = 1;

constexpr int TICKS_LIMIT = (
  22                            // Note duratian
  * 32                          // Pattern length (in notes)

  // Update pattern before it is used
  - SOUND_MUSIC_BUFFERSIZE * 2
  / 90                          // Samples per tick @ 11025 Hz
);

void startMusic() {
  gb.sound.playSong(&Gamebuino_Meta::adaptiveSong, true);
}

bool isMusicUpdateDue() {
  return (
    gb.sound.songPatternIndex() != pattern_to_update &&
    gb.sound.ticksPlayedInSongPattern() >= TICKS_LIMIT
  );
}

void resetMusic() {
  pattern_to_update = (gb.sound.songPatternIndex() + 1) % 2;
}

void updateMusic() {
  assertTrue(gb.sound.songPatternIndex() != pattern_to_update);

  int layer = 0;
  int num_tunes = 0;
  auto tunes = Gamebuino_Meta::adaptivePatternTunes[pattern_to_update];

  for (auto& llc : liveliness_checks) {
    int level = std::max(
      llc.liveliness(),
      cell_count_histories[layer].numCells()
    );
    if (level > 0) {
      level = std::min(3, level / 100);
      tunes[num_tunes++] = Gamebuino_Meta::adaptiveTunes[
        layer * 8 + level * 2 + pattern_to_update
      ];
    }

    ++layer;
  }
  assertTrue(num_tunes > 0);
  Gamebuino_Meta::adaptivePatterns[pattern_to_update]->numTunes = num_tunes;

  pattern_to_update = 1 - pattern_to_update;
}
